### ISSUE TITLE
Arduino Research

### ISSUE THREAD

**Issue by taylorajez** [GamesTwoSpring2015/Project2.5D#11]

**Comment by taylorajez** [comment]
Hey guys, I think this basic model would do what we want. the Arduino UNO Rev3
http://store.arduino.cc/product/A000066
![d94148ecca27de89ddb740749db8d9cf image 538x354](https://cloud.githubusercontent.com/assets/7369261/6090725/f8fb3c38-ae52-11e4-86b8-f5c15e04e0a5.jpg)

**Comment by taylorajez** [comment]
@daihoshi @sofoj1 @TJpenguin15

**Comment by daihoshi** [comment]
@taylorajez29  I do believe I have one of those in my room at home with a bunch of wires we could use.

**Comment by taylorajez** [comment]
That would be awesome if you're willing to volunteer that. Post if you want to use it for this project or not @daihoshi

**Comment by sofoj1** [comment]
Oh wow. Yeah, this should work nicely. We'll probably need the wires and stuff, so that's great @daihoshi

**Comment by sofoj1** [comment]
The Arduino UNO is being used.
