### ISSUE TITLE
Processor Research

### ISSUE THREAD

**Issue by sofoj1** [GamesTwoSpring2015/Project2.5D#3]
Research processor choices for the final build, composing ideas into a well thought out document.

**Comment by sofoj1** [comment]
@mcnallm2

**Comment by taylorajez** [comment]
From what I can see the Raspberry Pi model with more RAM is sold out currently so the B+ model is our best bet.
Raspberry Pi RASPBERRY PI B+
http://www.alliedelec.com/raspberry-pi-raspberry-pi-b-/70377493/
![70377493_large](https://cloud.githubusercontent.com/assets/7369261/6094955/f31d8496-af11-11e4-8de5-82d6de74473e.jpg)

**Comment by sofoj1** [comment]
The Raspberry Pi 2 is being used.
