### ISSUE TITLE
Concept Art

### ISSUE THREAD

**Issue by sofoj1** [GamesTwoSpring2015/Project2.5D#6]
Ideas and concepts for character and plot development.

**Comment by sofoj1** [comment]
@TJpenguin15

**Comment by taylorajez** [comment]
Hey guys, just reblogged a bunch of character concepts from other games to the Tumblr blog. Hope that helps.

**Comment by taylorajez** [comment]
Just realized that we have this nifty +1 button, we could post concept art here and "vote"  on it.

**Comment by sofoj1** [comment]
![rocketcog 1](https://cloud.githubusercontent.com/assets/10787324/6239582/228521ee-b6d3-11e4-98e2-5860ed07facc.png)
![rocketfuel](https://cloud.githubusercontent.com/assets/10787324/6239583/24eda29e-b6d3-11e4-97f5-fd65931dd3aa.png)
![rocketscrewdriver](https://cloud.githubusercontent.com/assets/10787324/6239585/27434008-b6d3-11e4-83ac-8fff3b13c595.png)
